### ISSUE TITLE
Set features = ["macros"] for docs.rs

### ISSUE THREAD

**Issue by dtolnay** [sfackler/rust-phf#150]
So that the macros are made visible by rustdoc on https://docs.rs/phf.

You can do this by adding to phf/Cargo.toml:

```toml
[package.metadata.docs.rs]
features = ["macros"]
```
